name: CI

on: push

jobs:
    build-job:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v4.2.0
            
          - name: Docker Login
            uses: docker/login-action@v3.3.0
            with:
                registry: actionsacrreg.azurecr.io
                username: ${{ secrets.ACR_USERNAME }}
                password: ${{ secrets.ACR_PASSWORD }}
           
            
        

        