name: CI

on: push

jobs:
    build-job:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v4.2.0

          - uses: azure/docker-login@v2
            with:
                  login-server: actionsacrreg.azurecr.io
                  username: ${{ secrets.ACR_USERNAME }}
                  password: ${{ secrets.ACR_PASSWORD }}

             
          - run: |
              docker build . -t actionsacrreg.azurecr.io/k8sdemo:${{ github.sha }}
              docker push actionsacrreg.azurecr.io/k8sdemo:${{ github.sha }}


          - uses: azure/k8s-set-context@v4
            with:
                method: kubeconfig
                kubeconfig: ${{ secrets.KUBE_CONFIG }}
                context: ACR-deployment # current-context from kubeconfig is used as default

          - uses: Azure/k8s-deploy@v5
            with:
               namespace: 'default'
               manifests: |
                   kubernetes/*
                   images: actionsacrreg.azurecr.io/k8sdemo:bf124c23308927e57222229fe9bf0dfb2ccabe4d
                   pull-images: true





           
            
        

        